PREFIX speech: <http://w3id.org/speech#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sioc: <http://rdfs.org/sioc/ns#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT DISTINCT ?creator_name ?speech ?speech_text
WHERE {
    ?speech a speech:Speech ;
       schema:text ?speech_text ;
       ?p_creator ?creator .
    ?creator ?p_name ?creator_name .
   VALUES ?p_creator {dc:creator sioc:has_creator}
   VALUES ?p_name {foaf:name sioc:name}
}
