PREFIX speech: <http://w3id.org/speech#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sioc: <http://rdfs.org/sioc/ns#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT DISTINCT ?thread (COUNT (?tweet) as ?count_tweet)
WHERE {
 ?thread a sioc:Thread ;
        sioc:container_of ?tweet .
 ?tweet a speech:Tweet ;
       dc:created ?date .
 FILTER(year(?date) = 2021)
}
GROUP BY ?thread ?date
ORDER BY DESC (?count_tweet)     
