PREFIX speech: <http://w3id.org/speech#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sioc: <http://rdfs.org/sioc/ns#>
PREFIX siocq: <http://rdfs.org/sioc/quotes#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT DISTINCT ?pparty_name ?quoted_account (COUNT (?tweet) as ?count_quotes)
WHERE {
 ?quoted_tweet a speech:Tweet ;
       siocq:quote_of ?tweet ;
       schema:text ?quoted_tweet_text ;
       sioc:has_creator ?quoted_account .
 ?tweet a speech:Tweet ;
       schema:text ?tweet_text ;
       sioc:has_creator ?account .
 ?pparty a speech:PoliticalParty ;
     foaf:holdsAccount ?account ;
     foaf:name ?pparty_name .
} GROUP BY ?pparty_name ?quoted_account
ORDER BY DESC (?count_quotes)
