PREFIX speech: <http://w3id.org/speech#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sioc: <http://rdfs.org/sioc/ns#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT DISTINCT ?ret_pparty_name ?pparty_name ?tweet_text
WHERE {
 ?tweet a speech:Tweet ;
       schema:text ?tweet_text ;
       sioc:has_creator ?ret_account .
 ?pparty a speech:PoliticalParty ;
      foaf:name ?pparty_name ;
      foaf:holdsAccount ?account .
 ?ret_pparty a speech:PoliticalParty ;
      foaf:name ?ret_pparty_name ;
     foaf:holdsAccount ?ret_account .
 ?account speech:retweets ?tweet .
}
