PREFIX speech: <http://w3id.org/speech#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sioc: <http://rdfs.org/sioc/ns#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT DISTINCT ?pparty_name ?hashtag_label ?speech_text
WHERE {
    ?pparty foaf:holdsAccount ?account ;
       foaf:name ?pparty_name .
    ?account sioc:creator_of ?speech .
    ?speech sioc:has_container ?hashtag ;
       schema:text ?speech_text .
    ?hashtag rdfs:label ?hashtag_label.
}  
