PREFIX speech: <http://w3id.org/speech#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sioc: <http://rdfs.org/sioc/ns#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT DISTINCT ?speech ?interaction_type ?interaction_count ?speech_text
WHERE {
    ?speech schema:interactionStatistic ?interactions ;
       schema:text ?speech_text .
    ?interactions schema:interactionType ?interaction_type;
       schema:userInteractionCount ?interaction_count .
}  
